#%RAML 1.0
title: URL2ME
baseUri: http://localhost:8080
version: v1

/generate:
  post:
    description: Shorten a URL and return the result
    queryParameters:
      url:
        example: |
        {
          "url": "https://google.com"
        }
    responses:
      200:
        body:
          application/json:
            example: |
            {
              "data": {
                "url": "localhost:8080/abcd"
              }
            }
      400:
        body:
          application/json:
            example: |
            {
              "message": |
              {
                "url": "must not be blank"
              }
            }
      500:
        body:
          application/json:
            example: |
            {
              "message": "Something went wrong"
            }
/{code}:
  get:
    description: Resolve the original URL from the given code and redirect to it
    responses:
      301:
        headers:
          Location:
            example: https://google.com
      404:
        body:
          application/json:
            example: |
            {
              "message": "The URL is invalid"
            }
      500:
        body:
          application/json:
            example: |
            {
              "message": "Something went wrong"
            }

